#spring:
#  application:
#    name: Hospitally
#  datasource:
#    url: jdbc:mysql://localhost:3306/hms
#    username: root
#    password: password123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  hikari:
#    maximum-pool-size: 10
#    minimum-idle: 5
#    idle-timeout: 30000
#    max-lifetime: 1800000

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Hospitally;encrypt=false
    username: sa
    password: Mypassword123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver